# Generated by Django 3.2.11 on 2022-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
