# Generated by Django 3.2.11 on 2022-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220206_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paymethod',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Cash on Pickup', 'Cash on Pickup')], default='medium', max_length=50),
        ),
    ]
