# Generated by Django 3.2.11 on 2022-02-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_paymethod_job_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('cop', 'Cash on Pickup'), ('cod', 'Cash on Delivery')], default='medium', max_length=30),
        ),
    ]
