# Generated by Django 3.2.11 on 2022-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Pickup', 'Cash on Pickup'), ('Cash on Delivery', 'Cash on Delivery')], default='medium', max_length=30),
        ),
    ]
